server:
  port: 9090

spring:
  application:
    name: onboarding-service

  datasource:
    url: jdbc:mysql://localhost:3306/onboarding_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false

# ----------------------------------------------------
# JWT CONFIGURATION
# ----------------------------------------------------
app:
  jwt:
    secret: "JH7d9w3h9HD92jDd92hD9s0Fjs92KfmA8shQ92mshQ82jsmA92jsmQ82jdmS8"
    expiration-ms: 3600000   # 1 hour in milliseconds

# ----------------------------------------------------
# APPLICATION INFORMATION
# ----------------------------------------------------
application:
  name: Onboarding Service
  version: 1.0.0
  description: Generic Configurable Onboarding Platform